# Generated by Django 5.0.3 on 2026-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('normal', 'Normal'), ('deviated', 'Deviated'), ('critical', 'Critical')], max_length=20)),
                ('anomaly_score', models.FloatField()),
                ('feedback', models.TextField(blank=True)),
            ],
        ),
    ]
